name: satori
description: Satori is a liveops server for games.
version: 1.3.0
repository: https://github.com/heroiclabs/nakama-dart
homepage: https://heroiclabs.com/docs/nakama/client-libraries/dart

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  chopper: ^8.1.0
  collection: ^1.19.1
  freezed_annotation: ^3.0.0  
  http: ^1.4.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  test: ^1.26.2
  
dev_dependencies:
  build_runner: ^2.5.4
  chopper_generator: ^8.1.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  swagger_dart_code_generator: ^3.0.3
  checked_yaml: ^2.0.4