name: nakama
description: Nakama is an open-source scalable game server that lets you focus
  on building games.
version: 1.2.0
repository: https://github.com/heroiclabs/nakama-dart
homepage: https://heroiclabs.com/docs/nakama/client-libraries/dart

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  fixnum: ^1.1.0
  freezed_annotation: ^3.0.0
  grpc: ^4.0.4
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  logging: ^1.1.0
  meta: ^1.8.0
  protobuf: ^4.0.0
  retrofit: ^4.1.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.3.2
  faker: ^2.0.0
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  retrofit_generator: ^9.2.0
  test: ^1.22.0
