name: nakama_example
description: A Flutter project to demonstrate the usage of the Nakama SDK.
publish_to: "none"

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  flutter_riverpod: ^2.6.1
  nakama:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
